[package]
name = "data"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
uuid = { version = "1.12", features = ["v4"] }
bson = { version = "2.13", features = ["chrono-0_4","uuid-1"] }
tokio = { version = "1.43", features = ["full"] }
futures = "0.3.31"
async-trait = "0.1.85"
chrono = "0.4.39"
serde_with = "3.12.0"
serde_derive = "1.0"
serde_json = "1.0"