[package]
name = "appointment_booking"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.85"
bson = "2.13.0"
chrono = "0.4.39"
futures = "0.3.31"
mongodb = "3.2"
serde = { version = "1.0.217", features = ["derive"] }

appointment_confirmation = {path = "../appointment_confirmation", version = "0.1.0"}
doctor_availability = {path = "../doctor_availability", version = "0.1.0"}
shared = {path = "../shared", version = "0.1.0"}