mod patient_repository_traits;
mod patient_appointment_repository_traits;

pub use patient_repository_traits::{PatientRepositoryResult, PatientRepositoryTrait};
pub use patient_appointment_repository_traits::{PatientAppointmentRepositoryResult, PatientAppointmentRepositoryTrait};
