mod doctor_read_repository_trait;
mod patient_repository_traits;
mod patient_appointment_repository_traits;


pub use doctor_read_repository_trait::DoctorReadRepositoryTrait;
pub use patient_repository_traits::PatientRepositoryTrait;
pub use patient_appointment_repository_traits::PatientAppointmentRepositoryTrait;
