[package]
name = "doctor_availability"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.85"
axum = "0.8.1"
bson = { version = "2.13", features = ["chrono-0_4","uuid-1"] }
chrono = { version = "0.4.39", features = ["serde"] }
futures = "0.3.31"
hyper = "1.5.2"
mongodb = "3.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_with = "3.12.0"
tokio = { version = "1.43", features = ["full"] }
uuid = { version = "1.12", features = ["v4"] }

shared = {path = "../shared", version = "0.1.0"}
