[package]
name = "doctor_appointment_management"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.13.0"
chrono = "0.4.39"

doctor_availability = {path = "../doctor_availability", version = "0.1.0"}
shared = {path = "../shared", version = "0.1.0"}
anyhow = "1.0.95"
async-trait = "0.1.85"
mongodb = "3.2"
serde = { version = "1.0.217", features = ["derive"] }
